apiVersion: 1
datasources:
- name: metrictank
  type: graphite
  access: proxy
  orgId: 1
  url: http://caddy:6061
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
  version: 1
  editable: true
- name: metrictank2
  type: graphite
  access: proxy
  orgId: 1
  url: http://caddy:6062
  isDefault: false
  jsonData:
     graphiteVersion: "1.1"
  version: 1
  editable: true
